### ISSUE TITLE
100.0 % of the requests are failing with HTTP 5xx.

### ISSUE THREAD

**Issue by noiji** [noiji/cambodia-school#3]
100.0 % of the requests are failing with HTTP 5xx.
Process default has been unhealthy for 1 hour 27 minutes (Target.ResponseCodeMismatch).
Following services are not running: application-web-1.

**Comment by noiji** [comment]
로그 확인 결과: Exception in thread "main" java.lang.UnsupportedClassVersionError: springboot/src/main/java/hellospring/demo/MainApplication has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 55.0

**Comment by noiji** [comment]
> 로그 확인 결과: Exception in thread "main" java.lang.UnsupportedClassVersionError: springboot/src/main/java/hellospring/demo/MainApplication has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 55.0

fixed by setting build.gradle like below but still the issue not fixed.
group = 'hello-spring'
version = '0.0.1-SNAPSHOT'
sourceCompatibility = '11'

**Comment by KarthikKalon** [comment]
> 

can you tell how do resolve this
